### ISSUE TITLE
PySCIPOpt installation error with Python 3.11 and Visual Studio packages

### ISSUE THREAD

**Issue by gerymueller** [scipopt/PySCIPOpt#659]
Hello, I am experiencing an issue while trying to install PySCIPOpt with Python 3.11 on my system. I have already installed SCIP and the required Visual Studio packages, but when I run pip install PySCIPOpt, I encounter the following error message:

<path_to_python>\include\cpython\unicodeobject.h(551,5): error C2059: syntax error: '}'
<path_to_python>\include\cpython\unicodeobject.h(554,1): error C2143: syntax error: missing '{' before '<L_brace>'
<path_to_python>\include\cpython\unicodeobject.h(558,1): error C2059: syntax error: '}'
<path_to_python>\include\cpython\unicodeobject.h(559,1): error C2143: syntax error: missing '{' before '<L_brace>'
<path_to_python>\include\cpython\unicodeobject.h(561,1): error C2059: syntax error: '}'
<path_to_python>\include\cpython\unicodeobject.h(562,1): error C2143: syntax error: missing '{' before '<L_brace>'

It seems that the problem is related to the compatibility between the current version of PySCIPOpt and Python 3.11, as there are some error messages regarding the use of undefined structures in the scip.c file.

I would appreciate any guidance or suggestions to resolve this issue. Thanks in advance!

**Comment by mattmilten** [comment]
Have you tried using Python 3.10? Or some other version of Python?

**Comment by gerymueller** [comment]
> Have you tried using Python 3.10? Or some other version of Python?

No, I haven't. I couldn't imagine that it wouldn't work on Python 3.11. But I'll give it a try.

**Comment by gerymueller** [comment]
> Have you tried using Python 3.10? Or some other version of Python?

It worked. Thank you very much, I would not have thought that!

**Comment by mattmilten** [comment]
FYI: The latest release of PySCIPOpt (version 4.3) is now also compatible with Python 3.10 and 3.11!
